// src/modules/ai/ai.service.ts

// import { callGeminiWithFallback, getGeminiFallbackChain } from './ai.providers';
import { Part } from '@google/generative-ai';
// import { env } from '../../config/env';

import {
  callGeminiWithFallback,
  callGroqWithFallback,
  getOCRProviderNames,
  getNLPProviderNames,
  getEditProviderNames,
} from './ai.providers';

import { OCR_PROMPT, buildNLPPrompt, buildEditPrompt } from './ai.prompts';

import {
  OCRResponse, NLPResponse, EditResponse,
  isAIError, 
  isOCRBlur, isOCRForeign, isOCRNormal,
} from './ai.types';

import {
  validateOCRResponse,
  validateNLPResponse,
  validateEditResponse,
} from './ai.validators';

// let geminiModel: GenerativeModel | null = null;

/* function getGeminiModel(): GenerativeModel {
  if (!env.GEMINI_API_KEY) {
    throw new Error('GEMINI_NOT_CONFIGURED');
  }

  if (!geminiModel) {
    const genAI = new GoogleGenerativeAI(env.GEMINI_API_KEY);
    geminiModel = genAI.getGenerativeModel({
      model: 'gemini-2.5-flash',
      safetySettings: [
        { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
        { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
      ],
    });
  }

  return geminiModel;
}
*/

// const MAX_RETRIES = 3;
// const RETRY_DELAYS = [1000, 3000, 9000];
// retry lama sudah dipindah ke ai.providers.ts

/*
async function callGeminiWithRetry(parts: Part[], retries = 0): Promise<string> {
  try {
    const result = await getGeminiModel().generateContent(parts);
    return result.response.text().trim();
  } catch (error) {
    if (error instanceof Error && error.message === 'GEMINI_NOT_CONFIGURED') {
      throw error;
    }

    if (retries >= MAX_RETRIES) {
      console.error('[AI] Gemini max retry exceeded:', error);
      throw new Error('GEMINI_MAX_RETRY_EXCEEDED');
    }

    console.warn(`[AI] Gemini retry ${retries + 1}/${MAX_RETRIES}`);
    await new Promise((resolve) => setTimeout(resolve, RETRY_DELAYS[retries]));
    return callGeminiWithRetry(parts, retries + 1);
  }
}
*/

// function parseGeminiJSON<T>(raw: string): T {
//   const cleaned = raw.replace(/```json\s*/gi, '').replace(/```\s*/gi, '').trim();
//   return JSON.parse(cleaned) as T;
// }

function parseAIJSON<T>(raw: string): T {
  let cleaned = raw.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  cleaned = cleaned
    .replace(/```json\s*/gi, '')
    .replace(/```\s*/gi, '')
    .trim();
  const jsonStart = cleaned.search(/[{[]/);
  if (jsonStart > 0) cleaned = cleaned.slice(jsonStart);
  const lastBrace = cleaned.lastIndexOf('}');
  const lastBracket = cleaned.lastIndexOf(']');
  const lastChar = Math.max(lastBrace, lastBracket);
  if (lastChar !== -1 && lastChar < cleaned.length - 1) {
    cleaned = cleaned.slice(0, lastChar + 1);
  }
  return JSON.parse(cleaned) as T;
}

// supaya tetap aman dengan ai.types
function buildMissingConfigResponse() {
  return {
    error: 'AI_NOT_CONFIGURED' as const,
    message: 'Fitur AI belum dikonfigurasi.',
  };
}

function buildBusyAIResponse() {
  return {
    error: 'AI_MAX_RETRY_EXCEEDED' as const,
    message: 'Layanan AI sedang sibuk, coba lagi nanti.',
  };
}

function buildRequestFailedResponse(message: string) {
  return {
    error: 'AI_REQUEST_FAILED' as const,
    message,
  };
}

// function buildOCRBridgePrompt(ocrRawText: string): string {
//   return [
//     OCR_PROMPT,
//     '',
//     'Berikut adalah hasil OCR mentah dari OCR.space.',
//     'Gunakan hanya teks OCR ini sebagai sumber data utama.',
//     'Jika teks OCR kosong, sangat buruk, atau tidak bisa dipahami, pertimbangkan case BLUR.',
//     '',
//     'OCR_TEXT_START',
//     ocrRawText,
//     'OCR_TEXT_END',
//   ].join('\n');
// }

// bridge OCR.space -> Groq sekarang sudah ditangani di ai.providers.ts

// export function getAIProviderNames(): string[] {
//   return getGeminiFallbackChain();
// }

export function getOCRProviders(): string[] {
  return getOCRProviderNames();
}

export function getNLPProviders(): string[] {
  return getNLPProviderNames();
}

export function getEditProviders(): string[] {
  return getEditProviderNames();
}

export async function extractFromImage(
  base64Image: string,
  mimeType: string = 'image/jpeg'
): Promise<OCRResponse> {
  try {
    // const ocrResult = await callOCRSpace(base64Image, mimeType);
    // console.log(`[AI] OCR raw text generated by ${ocrResult.provider}`);

    // const bridgedPrompt = buildOCRBridgePrompt(ocrResult.text);
    // const { text, model, provider } = await callGroqWithFallback(bridgedPrompt);
    // console.log(`[AI] Structured OCR generated by ${provider}/${model}`);

    const parts: Part[] = [
      { text: OCR_PROMPT },
      { inlineData: { data: base64Image, mimeType } },
    ];

    const { text, model } = await callGeminiWithFallback(parts);
    console.log(`[AI] OCR pipeline generated by ${model}`);
    
    /*
    const raw = await callGeminiWithRetry([
      { text: OCR_PROMPT },
      { inlineData: { data: base64Image, mimeType } },
    ]);
    */

    // const raw = text;
    // const parsed = parseGeminiJSON<OCRResponse>(raw);
    const raw = text;
    const parsed = parseAIJSON<OCRResponse>(raw);
    const validated = validateOCRResponse(parsed);

    if ('case' in validated) {
      if (isOCRBlur(validated)) {
        console.log('[AI] OCR case: BLUR -', validated.message);
      } else if (isOCRForeign(validated)) {
        console.log(
          `[AI] OCR case: FOREIGN - ${validated.originalCurrency} ${validated.originalAmount} -> IDR ${validated.totalAmount}`
        );
      } else if (isOCRNormal(validated)) {
        console.log(
          `[AI] OCR case: NORMAL - ${validated.merchantName} Rp${validated.totalAmount}`
        );
      }
    }

    return validated;
  } catch (error) {
    // if (
    //   error instanceof Error &&
    //   (error.message === 'OCR_SPACE_NOT_CONFIGURED' || error.message === 'GROQ_NOT_CONFIGURED')
    // ) {
    //   return buildMissingConfigResponse();
    // }

    // if (
    //   error instanceof Error &&
    //   (error.message === 'OCR_SPACE_MAX_RETRY_EXCEEDED' || error.message === 'GROQ_MAX_RETRY_EXCEEDED')
    // ) {
    //   return buildBusyAIResponse();
    // }

    // if (
    //   error instanceof Error &&
    //   (error.message === 'OCR_SPACE_REQUEST_FAILED' || error.message === 'GROQ_REQUEST_FAILED')
    // ) {
    //   console.error('[AI] OCR provider request failed:', error);
    //   return buildRequestFailedResponse('Gagal memproses gambar struk.');
    // }

    if (
      error instanceof Error &&
      (
        error.message === 'GEMINI_NOT_CONFIGURED' ||
        error.message === 'OCR_SPACE_NOT_CONFIGURED' ||
        error.message === 'GROQ_NOT_CONFIGURED'
      )
    ) {
      return buildMissingConfigResponse();
    }

    if (
      error instanceof Error &&
      (
        error.message === 'GEMINI_MAX_RETRY_EXCEEDED' ||
        error.message === 'OCR_SPACE_MAX_RETRY_EXCEEDED' ||
        error.message === 'GROQ_MAX_RETRY_EXCEEDED'
      )
    ) {
      return buildBusyAIResponse();
    }

    if (
      error instanceof Error &&
      (
        error.message === 'GEMINI_REQUEST_FAILED' ||
        error.message === 'OCR_SPACE_REQUEST_FAILED' ||
        error.message === 'GROQ_REQUEST_FAILED'
      )
    ) {
      console.error('[AI] OCR provider request failed:', error);
      return buildRequestFailedResponse('Gagal memproses gambar struk.');
    }

    console.error('[AI] OCR error:', error);
    return buildRequestFailedResponse('Gagal memproses gambar struk.');
  }
}

export async function extractFromText(
  message: string,
  categories: string[]
): Promise<NLPResponse> {
  try {
    // const parts: Part[] = [
    //   { text: buildNLPPrompt(message, categories) },
    // ];
    // const { text, model } = await callGeminiWithFallback(parts);
    // console.log(`[AI] Response generated by ${model}`);

    const prompt = buildNLPPrompt(message, categories);
    const { text, model, provider } = await callGroqWithFallback(prompt);
    console.log(`[AI] Response generated by ${provider}/${model}`);
    // const raw = text;
    // const parsed = parseGeminiJSON<NLPResponse>(raw);
    const raw = text;
    const parsed = parseAIJSON<NLPResponse>(raw);

// ← tambah ini
if (isAIError(parsed)) {
  console.log('[AI] NLP returned error:', parsed.error, parsed.message);
  return parsed;
}

    const validated = validateNLPResponse(parsed);

    console.log(
      '[AI] NLP success:',
      (validated as any).amount,
      (validated as any).suggestedCategory
    );

    return validated;
  } catch (error) {
    if (error instanceof Error && error.message === 'GROQ_NOT_CONFIGURED') {
      return buildMissingConfigResponse();
    }

    if (error instanceof Error && error.message === 'GROQ_MAX_RETRY_EXCEEDED') {
      return buildBusyAIResponse();
    }

    if (error instanceof Error && error.message === 'GROQ_REQUEST_FAILED') {
      console.error('[AI] NLP provider request failed:', error);
      return buildRequestFailedResponse('Gagal memproses pesan teks.');
    }

    console.error('[AI] NLP error:', error);
    return buildRequestFailedResponse('Gagal memproses pesan teks.');
  }
}

export async function applyUserCorrection(
  correction: string,
  currentData: object
): Promise<EditResponse> {
  try {
    // const parts: Part[] = [
    //   { text: buildEditPrompt(correction, currentData) },
    // ];
    // const { text, model } = await callGeminiWithFallback(parts);
    // console.log(`[AI] Response generated by ${model}`);

    const prompt = buildEditPrompt(correction, currentData);
    const { text, model, provider } = await callGroqWithFallback(prompt);
    console.log(`[AI] Response generated by ${provider}/${model}`);

    // const raw = text;
    // const parsed = parseGeminiJSON<EditResponse>(raw);
    const raw = text;
    const parsed = parseAIJSON<EditResponse>(raw);

// ← tambah ini
if (isAIError(parsed)) {
  console.log('[AI] Edit returned error:', parsed.error, parsed.message);
  return parsed;
}

const validated = validateEditResponse(parsed);

    console.log('[AI] Edit applied:', correction);
    return validated;
  } catch (error) {
    if (error instanceof Error && error.message === 'GROQ_NOT_CONFIGURED') {
      return buildMissingConfigResponse();
    }

    if (error instanceof Error && error.message === 'GROQ_MAX_RETRY_EXCEEDED') {
      return buildBusyAIResponse();
    }

    if (error instanceof Error && error.message === 'GROQ_REQUEST_FAILED') {
      console.error('[AI] Edit provider request failed:', error);
      return buildRequestFailedResponse('Gagal memproses koreksi.');
    }

    console.error('[AI] Edit error:', error);
    return buildRequestFailedResponse('Gagal memproses koreksi.');
  }
}